title: Harshal LADHE

description: Software Engineer | Freelancer | Learner

url: "https://shivam091.github.io"

# The language of the webpage
lang: en

# The time zone of the webpage
timezone: Asia/Kolkata

plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate-v2

permalink: /post/:slug

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: text
    line_numbers: false

google_analytics:
  id: "G-W5GHEJ51PD"

include:
  - assets

exclude:
  - README.md
  - LICENSE.md

sitemap:
  minify: true

sass:
  sass_dir: _sass
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

collections:
  series:
    output: false

jekyll-archives:
  enabled:
    - tags
    - categories
  layout: archive
  permalinks:
    tag: /tag/:name/
    category: /category/:name/

pagination:
  enabled: true
  title: ":title - Page :num"
  permalink: pretty
  trail:
    before: 2
    after: 2
  sort_reverse: true

author:
  name: Harshal LADHE
  roles:
    - software engineer
    - freelancer
    - lifelong learner
    - entrepreneur
  email: harshal.ladhe.1@gmail.com
  github: shivam091
  linkedin: shivam091
  instagram: taurusian_soul
  resume: /assets/docs/resume.pdf

breadcrumbs:
  enabled: true

post:
  author:
    default: harshal
  read_time:
    words_per_minute: 180
  retro_counter:
    enabled: true

pinned_posts:
  enabled: true

featured_posts:
  enabled: true

recently_updated_posts:
  enabled: true
  limit: 5

popular_categories:
  enabled: true
  limit: 5

trending_tags:
  enabled: true
  limit: 10
  max_posts: 15
  decay_strategy: exponential # log or linear
  normalization: true

related_post:
  enabled: true
  limit: 3
  tag_score: 1.0
  category_score: 0.5
  fallback_to_recent: true # Optional: fallback if not enough matches
