title: Harshal LADHE

description: Software Engineer | Freelancer | Learner

url: "https://shivam091.github.io"

# The language of the webpage
lang: en

# The time zone of the webpage
timezone: Asia/Kolkata

plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-seo-tag

permalink: /post/:year/:month/:day/:title

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: text
    line_numbers: false

google_analytics:
  id: "G-W5GHEJ51PD"

include:
  - assets

exclude:
  - README.md
  - LICENSE.md

sass:
  sass_dir: _sass
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

jekyll-archives:
  enabled:
    - tags
    - categories
  layout: archive
  permalinks:
    tag: /tag/:name/
    category: /category/:name/

author:
  name: Harshal LADHE
  roles:
    - software engineer
    - freelancer
    - lifelong learner
    - entrepreneur
  email: harshal.ladhe.1@gmail.com
  github_username: shivam091
  linkedin_username: shivam091
  instagram_username: taurusian_soul
  resume: /assets/docs/resume.pdf

nav:
  - { title: "Home", icon: "home", href: "/" }
  - { title: "About", icon: "info-circle", href: "/about" }
  - { title: "Categories", icon: "folder", href: "/categories" }
  - { title: "Tags", icon: "tag", href: "/tags" }
  - { title: "Posts", icon: "list", href: "/posts" }

color_schemes:
  - { key: "system", display_label: "System", icon: "device-desktop" }
  - { key: "light", display_label: "Light", icon: "sun" }
  - { key: "dark", display_label: "Dark", icon: "moon" }

posts:
  read_time:
    words_per_minute: 180
