source "https://rubygems.org"

ruby "~> 3.3"

gem "rails", "~> 8.0"
gem "puma", ">= 5.0"
gem "sprockets-rails"

gem "mongoid", "~> 9.0"
gem "devise"
gem "turbo-rails"
gem "stimulus-rails"
gem "tailwindcss-rails"

gem "jbuilder"
gem "tzinfo-data", platforms: %i[windows jruby]
gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[mri windows linux]
  gem "brakeman", require: false
end

group :development do
  gem "web-console"
end
