source "https://rubygems.org"

ruby "~> 3.3"

gem "rails", "~> 8.0"
gem "puma", ">= 5.0"

gem "mongoid", "~> 9.0"
gem "rack-cors"
gem "jwt"

gem "tzinfo-data", platforms: %i[windows jruby]
gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[mri windows linux]
end
